### ISSUE TITLE
esm3 not working on google colab

### ISSUE THREAD

**Issue by sokrypton** [evolutionaryscale/esm#89] opened 2024-08-27 14:55 UTC
Not sure if this is a colab issue or GPU T4 or esm3 issue.

But today suddenly things stopped working for me.

<img width="757" alt="image" src="https://github.com/user-attachments/assets/b61d22c8-03b4-4b70-828b-611a1755c437">

See:
https://colab.research.google.com/drive/1n6a__ieW0Icpo-4x0XRzC-IgLZR7Wzl2?usp=sharing

**Comment by santiag0m** [comment] 2024-08-27 20:51
Thanks for letting us know!

I was able to reproduce the error by running `!pip install sentencepiece==0.1.91` which seems to be the culprit.

**Comment by santiag0m** [comment] 2024-08-27 20:54
Possibly related to this: https://github.com/google/sentencepiece/issues/505

**Comment by santiag0m** [comment] 2024-08-27 21:17
Seems to be a problem with dependency conflicts caused by `biotite` due to the recent release of the 1.0.0 version 10 hours ago: https://pypi.org/project/biotite/1.0.0/

Pinning `biotite==0.41.2` solves the issue

**Comment by santiag0m** [comment] 2024-08-27 21:22
@sokrypton We will be releasing an updated pip wheel soon.

In the meanwhile you can install esm on google colab by running:

```python
!pip install biotite==0.41.2
!pip install esm
```

**Comment by sokrypton** [comment] 2024-08-27 21:24
Awesome! thanks!

**Comment by padix-key** [comment] 2024-08-28 08:56
@santiag0m Did you investigate which Biotite dependency leads to the conflict? First I assumed the `numpy >= 2.0` restriction of `biotraj` causes this (https://github.com/biotite-dev/biotraj/pull/11), but this seems not be the case here, right?

**Comment by santiag0m** [comment] 2024-08-28 19:59
@padix-key I wasn't able to pinpoint exactly what it was. But I do think it is the combination of `biotraj + numpy`, you can see in the link that @sokrypton shared that it is traversing versions of the `transformers` package to satisfy the constraints for `biotraj`

**Comment by padix-key** [comment] 2024-08-28 22:06
We just released a patch version for `biotraj`, relaxing the NumPy version pin. Could you check if it works again?

**Comment by santiag0m** [comment] 2024-08-30 22:09
We have released a new version of the package pinning `biotite` but can confirm that installing the previous version of `esm` (which does not include the fix from our side), works:

`!pip install esm==3.0.3`

**Comment by santiag0m** [comment] 2024-08-30 22:10
Closing as both old (`<3.04`) and the current (`3.0.4`) versions of `esm` should be working.

**Closed by santiag0m** 2024-08-30 22:10 UTC
